
const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '../../js/data/interviewPrep');
function q(id, topic, difficulty, question, options, correctAnswer, explanation) {
  return { id, topic, difficulty, question, options, correctAnswer, explanation };
}

console.log('Generating AI & Machine Learning questions (15 topics * 10 = 150 MCQs)...');
const aimlQuestions = [

  q('aiml_fnd_1', 'AI vs ML vs Deep Learning', 'Easy',
    'What is the hierarchical relationship between AI, Machine Learning, and Deep Learning?',
    ['They are three completely unrelated disciplines', 'AI is the broad umbrella concept; Machine Learning is a subset of AI; Deep Learning is a specialized subset of Machine Learning using multi-layered neural networks', 'Deep Learning encompasses AI; AI is a subset of ML', 'Machine Learning is hardware; Deep Learning is software'], 1,
    'AI is the overarching field of creating intelligent machines. ML is the subset of AI focused on learning patterns from data without explicit programming. Deep Learning is the subfield of ML employing deep artificial neural networks.'),
  q('aiml_fnd_2', 'AI vs ML vs Deep Learning', 'Easy',
    'What distinguishes Machine Learning from traditional rule-based programming?',
    ['ML requires no computers', 'In traditional programming, humans write explicit rules and input data to produce answers; in ML, the algorithm is fed data and answers to learn the underlying rules/patterns automatically', 'Traditional programming is always faster than ML', 'ML can only process numbers under 100'], 1,
    'Traditional programming takes Data + Rules -> Answers. Machine Learning takes Data + Answers -> Learned Rules (statistical models).'),
  q('aiml_fnd_3', 'AI vs ML vs Deep Learning', 'Easy',
    'What are the three primary paradigms of Machine Learning?',
    ['Frontend, Backend, Database', 'Supervised Learning, Unsupervised Learning, and Reinforcement Learning', 'Static, Dynamic, Continuous', 'Linear, Quadratic, Exponential'], 1,
    'The 3 classic ML paradigms: Supervised (learning with labeled data), Unsupervised (discovering hidden patterns in unlabeled data), and Reinforcement (learning optimal actions via trial-and-error rewards).'),
  q('aiml_fnd_4', 'AI vs ML vs Deep Learning', 'Easy',
    'What is "Narrow AI" (Weak AI) versus "General AI" (AGI)?',
    ['Narrow AI is for smartphones; General AI is for supercomputers', 'Narrow AI is designed to perform a specific dedicated task (e.g. chess, image recognition); General AI possesses human-like generalized intelligence capable of learning any intellectual task', 'Narrow AI has fewer lines of code', 'General AI has already been achieved by calculators'], 1,
    'All existing AI today (ChatGPT, AlphaFold, Siri, self-driving cars) is Narrow AI focused on specific domains. Artificial General Intelligence (AGI) remains theoretical: machines capable of autonomous cross-domain human-level cognitive reasoning.'),
  q('aiml_fnd_5', 'AI vs ML vs Deep Learning', 'Medium',
    'What is the primary advantage of Deep Learning over classical ML (like Random Forest or SVM) when dealing with raw unstructured data (images, audio, text)?',
    ['Deep learning requires zero training data', 'Deep learning performs automated hierarchical feature representation learning directly from raw data, eliminating tedious manual domain feature engineering', 'Deep learning models are always explainable and transparent', 'Deep learning runs without GPUs'], 1,
    'Classical ML requires domain experts to manually engineer and extract features. Deep learning networks automatically learn hierarchical representations (edges -> shapes -> object parts -> whole objects) from raw pixel/token inputs.'),
  q('aiml_fnd_6', 'AI vs ML vs Deep Learning', 'Medium',
    'What is the Turing Test and what was its historical significance?',
    ['A benchmark for CPU clock frequency', 'A test proposed by Alan Turing where a human evaluator engages in a blind text conversation with a machine and another human; if evaluator cannot reliably tell machine from human, the machine exhibits intelligence', 'A test proving mathematical theorems', 'A benchmark for cryptographic encryption'], 1,
    'Alan Turing\'s 1950 "Imitation Game" proposed assessing machine intelligence operationally: if a computer\'s verbal responses are indistinguishable from a human\'s, it can be said to think.'),
  q('aiml_fnd_7', 'AI vs ML vs Deep Learning', 'Medium',
    'What is "Feature Engineering" in classical machine learning?',
    ['Designing computer hardware features', 'The process of selecting, transforming, and creating domain-specific mathematical variables/features from raw data to improve ML model accuracy and performance', 'Writing automated unit tests for AI models', 'Creating user interfaces for AI products'], 1,
    'Feature engineering transforms raw observations (dates, text, categorical records) into informative representations (one-hot encoding, normalization, aggregations) that best expose underlying patterns to ML algorithms.'),
  q('aiml_fnd_8', 'AI vs ML vs Deep Learning', 'Medium',
    'What is the "Curse of Dimensionality" in machine learning?',
    ['A theoretical bug in Python compilers', 'As the number of input features (dimensions) increases, the volume of the feature space grows exponentially, making data points extremely sparse and distances between points indistinguishable', 'When an AI model runs out of hard drive storage', 'When matrices become non-invertible'], 1,
    'In high-dimensional spaces, data points become exponentially isolated. Distance metrics (Euclidean) lose discriminatory power, requiring exponentially more training samples to avoid severe overfitting.'),
  q('aiml_fnd_9', 'AI vs ML vs Deep Learning', 'Hard',
    'What is Moravec\'s Paradox in Artificial Intelligence?',
    ['Computers cannot multiply large numbers', 'Contrary to traditional expectations, high-level reasoning and abstract logic (chess, calculus) require relatively little computational effort, whereas low-level sensorimotor skills (walking, visual perception, object grasping) require enormous computational resources', 'AI models learn faster when written in C', 'Neural networks fail on floating point inputs'], 1,
    'Hans Moravec observed: it is comparatively easy to make computers exhibit adult-level performance on intelligence tests or playing checkers, but difficult to give them the motor and perceptual skills of a one-year-old child.'),
  q('aiml_fnd_10', 'AI vs ML vs Deep Learning', 'Hard',
    'What is the "No Free Lunch" Theorem for machine learning?',
    ['AI researchers must pay for lunch', 'No single machine learning algorithm is universally superior to all other algorithms across every conceivable problem; every algorithm makes inductive assumptions that excel on some datasets and fail on others', 'All ML models require cloud subscriptions', 'Unsupervised learning is always cheaper than supervised'], 1,
    'Wolpert and Macready proved: averaged across all possible data distributions, every classification algorithm has the same expected error rate. Algorithm success depends on how well its inductive biases align with the specific problem distribution.'),

  q('aiml_sl_1', 'Supervised Learning', 'Easy',
    'What is the fundamental difference between Regression and Classification in supervised learning?',
    ['Regression uses neural networks; classification uses trees', 'Regression predicts continuous numerical values (e.g. house prices); Classification predicts discrete categorical labels (e.g. spam or not spam)', 'Regression is unsupervised; classification is supervised', 'Classification cannot predict probabilities'], 1,
    'Regression targets continuous real-valued outputs (quantities, prices, temperatures). Classification targets discrete categorical class labels (binary or multi-class).'),
  q('aiml_sl_2', 'Supervised Learning', 'Easy',
    'What is the mathematical hypothesis function of simple Linear Regression?',
    ['y = mx^2 + c', 'y = w * x + b (or y = β0 + β1*x)', 'y = 1 / (1 + e^-x)', 'y = log(x)'], 1,
    'Simple linear regression models the relationship between independent feature x and dependent target y as a straight line: y = w*x + b, where w is weight (slope) and b is bias (intercept).'),
  q('aiml_sl_3', 'Supervised Learning', 'Easy',
    'What function does Logistic Regression use to map real-valued predictions into probabilities between 0 and 1?',
    ['ReLU function', 'Sigmoid / Logistic function: σ(z) = 1 / (1 + e^-z)', 'Linear function', 'Step function'], 1,
    'The Sigmoid function maps any real-valued number (-∞ to +∞) into an S-shaped curve between 0 and 1, interpreting output as the probability of the positive class.'),
  q('aiml_sl_4', 'Supervised Learning', 'Easy',
    'How does a K-Nearest Neighbors (KNN) algorithm classify a new query data point?',
    ['By training a deep neural network', 'By computing the distance to all training samples, identifying the K closest points, and assigning the majority class among those K neighbors', 'By drawing a decision boundary line with gradient descent', 'By clustering data into K groups using centroids'], 1,
    'KNN is a non-parametric, lazy learning algorithm: at query time, it computes distances (Euclidean/Manhattan) to all points in memory and votes the majority label of the nearest K points.'),
  q('aiml_sl_5', 'Supervised Learning', 'Medium',
    'What is the role of the "Margin" and "Support Vectors" in Support Vector Machines (SVM)?',
    ['Support vectors are computer RAM units', 'SVM seeks the optimal hyperplane that maximizes the margin (perpendicular distance) between the boundary and the closest data points of opposing classes (which are the Support Vectors)', 'Margins define the training learning rate', 'Support vectors are weights that equal zero'], 1,
    'SVM finds the separating hyperplane with the maximum margin. The critical training instances lying directly on the margin boundary that dictate the hyperplane position are called Support Vectors.'),
  q('aiml_sl_6', 'Supervised Learning', 'Medium',
    'What criteria are commonly used to evaluate splits in Decision Tree algorithms (e.g. CART, ID3)?',
    ['Accuracy and Loss', 'Gini Impurity, Information Gain (Entropy reduction), and Variance Reduction', 'Euclidean Distance and Cosine Similarity', 'Gradient and Hessian'], 1,
    'Decision trees choose split points that maximize purity: CART uses Gini Impurity; ID3/C4.5 uses Information Gain based on Shannon Entropy; regression trees use variance reduction.'),
  q('aiml_sl_7', 'Supervised Learning', 'Medium',
    'What is the "Kernel Trick" in Support Vector Machines?',
    ['A cheat code to speed up SVM training', 'Implicitly mapping non-linearly separable data into a higher-dimensional space using a kernel function (e.g. RBF, Polynomial) where a linear hyperplane can separate the classes, without computing explicit high-dimensional coordinates', 'Running SVM on GPU kernels', 'Deleting outliers from data'], 1,
    'The kernel trick replaces costly high-dimensional dot products with equivalent kernel functions (like Gaussian RBF: `K(x, y) = exp(-γ||x-y||^2)`), enabling non-linear boundaries efficiently.'),
  q('aiml_sl_8', 'Supervised Learning', 'Medium',
    'What is the difference between "Bagging" (e.g. Random Forest) and "Boosting" (e.g. XGBoost, LightGBM)?',
    ['Bagging is for regression; boosting for classification', 'Bagging trains multiple independent base models in parallel on bootstrap subsets and averages them (reduces variance); Boosting trains models sequentially, where each new model focuses on correcting errors of prior models (reduces bias)', 'Boosting trains models in parallel; bagging sequentially', 'Random Forest uses deep neural networks'], 1,
    'Bagging (Bootstrap Aggregation) trains trees in parallel on random data slices, reducing variance. Boosting trains trees sequentially where each successive tree fits pseudo-residuals of previous trees, reducing bias and variance.'),
  q('aiml_sl_9', 'Supervised Learning', 'Hard',
    'Why is Ordinary Least Squares (OLS) sensitive to Multicollinearity in multiple linear regression?',
    ['It causes computer overheating', 'When predictor features are highly linearly correlated, the matrix (X^T * X) becomes nearly singular (non-invertible), causing coefficient estimates to become unstable with huge standard errors', 'It converts regression to classification', 'It forces all weights to zero'], 1,
    'When features are collinear, `(X^T * X)^-1` cannot be computed accurately. Small fluctuations in data cause massive swings in coefficient magnitudes and signs, destroying model interpretability.'),
  q('aiml_sl_10', 'Supervised Learning', 'Hard',
    'What is the "Out-of-Bag" (OOB) error in Random Forest and how does it replace cross-validation?',
    ['An error thrown when RAM runs out', 'Because each tree is trained on a bootstrap sample (~63.2% of data), the remaining ~36.8% unselected samples (OOB data) act as an internal validation set, providing an unbiased validation score without explicit cross-validation', 'A metric measuring leaf node depth', 'An error thrown when trees diverge'], 1,
    'Sampling with replacement leaves approximately (1 - 1/e) ≈ 36.8% of training samples out of each tree\'s dataset. Evaluating trees on their respective out-of-bag samples provides an accurate, built-in validation metric.'),

  q('aiml_ul_1', 'Unsupervised Learning', 'Easy',
    'What is the defining characteristic of Unsupervised Learning?',
    ['Algorithms are trained without computers', 'Algorithms are provided input data without any target labels or ground truth outcomes, discovering inherent patterns, groupings, or representations autonomously', 'Algorithms require continuous human intervention', 'Models only predict true or false'], 1,
    'In unsupervised learning, datasets contain features X with no corresponding target labels Y. The objective is to discover underlying structures, cluster memberships, or low-dimensional manifolds.'),
  q('aiml_ul_2', 'Unsupervised Learning', 'Easy',
    'What does the K-Means clustering algorithm do?',
    ['Classifies images using neural networks', 'Partitions N observations into K distinct clusters such that each observation belongs to the cluster with the nearest mean (centroid)', 'Sorts numbers in ascending order', 'Removes null values from datasets'], 1,
    'K-Means iteratively partitions data into K non-overlapping clusters by minimizing the within-cluster sum of squares (WCSS) distance between points and their assigned cluster centroid.'),
  q('aiml_ul_3', 'Unsupervised Learning', 'Easy',
    'What is Principal Component Analysis (PCA) primarily used for?',
    ['Predicting stock market trends', 'Dimensionality reduction: transforming correlated high-dimensional features into a smaller set of orthogonal, uncorrelated variables (principal components) preserving maximum variance', 'Clustering customer segments', 'Training deep neural networks'], 1,
    'PCA projects high-dimensional data onto orthogonal axes of maximum variance, shrinking feature count for compression, noise reduction, and 2D/3D visualization while minimizing information loss.'),
  q('aiml_ul_4', 'Unsupervised Learning', 'Easy',
    'What is the "Elbow Method" used for in K-Means clustering?',
    ['To measure developer elbow strain', 'To determine the optimal number of clusters K by plotting Within-Cluster Sum of Squares (Inertia) against K and locating the inflection point ("elbow")', 'To detect outlier data points', 'To initialize centroids randomly'], 1,
    'As K increases, WCSS naturally decreases. The "elbow" marks the point of diminishing returns where adding further clusters yields negligible reduction in WCSS, indicating a natural cluster count.'),
  q('aiml_ul_5', 'Unsupervised Learning', 'Medium',
    'What is the difference between Agglomerative and Divisive Hierarchical Clustering?',
    ['Agglomerative is for numbers; Divisive for text', 'Agglomerative is bottom-up (each point starts in its own cluster and merges sequentially); Divisive is top-down (all points start in one giant cluster and split recursively)', 'Divisive requires K to be set; Agglomerative does not', 'They produce identical trees without math'], 1,
    'Agglomerative clustering merges closest pairs of clusters bottom-up into a dendrogram. Divisive clustering splits the entire dataset top-down iteratively until singletons remain.'),
  q('aiml_ul_6', 'Unsupervised Learning', 'Medium',
    'What is a "Dendrogram" in hierarchical clustering?',
    ['A diagram of computer file systems', 'A tree-like diagram that illustrates the arrangement and sequence of cluster merges or splits and the distance between clusters at each step', 'A neural network architecture', 'A scatter plot of principal components'], 1,
    'A dendrogram visually represents the hierarchical clustering tree. Cutting the dendrogram horizontally at a chosen vertical height/distance determines the number of clusters.'),
  q('aiml_ul_7', 'Unsupervised Learning', 'Medium',
    'How does DBSCAN (Density-Based Spatial Clustering of Applications with Noise) differ from K-Means?',
    ['DBSCAN requires defining K in advance', 'DBSCAN identifies clusters of arbitrary non-spherical shapes based on density (min points within epsilon radius) and automatically labels sparse outliers as noise, requiring no predefined K', 'K-Means can detect arbitrary shapes; DBSCAN cannot', 'DBSCAN only works on 1-dimensional data'], 1,
    'K-Means assumes spherical clusters and assigns every point (including outliers) to a centroid. DBSCAN groups contiguous dense regions, handles arbitrary irregular shapes, and marks isolated points as noise.'),
  q('aiml_ul_8', 'Unsupervised Learning', 'Medium',
    'What is the "Silhouette Score" in clustering evaluation and what is its range?',
    ['A metric from 0 to 100 measuring CPU temperature', 'A metric ranging from -1 to +1 measuring how similar an object is to its own cluster (cohesion) compared to neighboring clusters (separation); closer to +1 indicates well-clustered points', 'A metric measuring hard drive storage', 'A metric measuring regression line slope'], 1,
    'Silhouette Score `s = (b - a) / max(a, b)`: `a` is mean intra-cluster distance, `b` is mean nearest-cluster distance. +1 indicates ideal clustering, 0 indicates overlapping clusters, and negative indicates misassigned samples.'),
  q('aiml_ul_9', 'Unsupervised Learning', 'Hard',
    'In PCA, what mathematical entities represent the directions of maximum variance and the amount of variance explained?',
    ['Gradient and Learning rate', 'Eigenvectors of the feature covariance matrix represent directions; their corresponding Eigenvalues represent the amount of variance explained along each axis', 'Weights and Biases of neural networks', 'Mean and Standard Deviation of labels'], 1,
    'Eigen decomposition (or SVD) of the data covariance matrix yields Eigenvectors (which form the principal component loading axes) and Eigenvalues (proportional to variance captured along each respective eigenvector).'),
  q('aiml_ul_10', 'Unsupervised Learning', 'Hard',
    'What is t-SNE (t-Distributed Stochastic Neighbor Embedding) and why is it preferred over PCA for visualizing complex non-linear data in 2D?',
    ['t-SNE is faster than PCA on 10 million rows', 'PCA preserves only global linear variance; t-SNE is a non-linear probabilistic technique that preserves local pairwise neighborhoods, revealing intricate non-linear clusters and manifolds in 2D/3D', 't-SNE can be used for feature engineering in regression', 'PCA converts non-linear data to linear automatically'], 1,
    't-SNE converts Euclidean distances into conditional probabilities in high- and low-dimensional spaces, minimizing Kullback-Leibler divergence. It clusters similar points closely, making it state-of-the-art for visual exploratory analysis.'),

  q('aiml_rl_1', 'Reinforcement Learning', 'Easy',
    'What are the core components in the standard Reinforcement Learning framework?',
    ['Input, Hidden Layer, Output', 'Agent, Environment, State, Action, and Reward', 'Dataset, Testset, Hyperparameters', 'Optimizer, Loss, Activation'], 1,
    'In RL, an autonomous Agent interacts with an Environment: observing current State `s`, taking Action `a`, receiving scalar Reward `r`, and transitioning to new State `s\'.'),
  q('aiml_rl_2', 'Reinforcement Learning', 'Easy',
    'What is the primary objective of an agent in Reinforcement Learning?',
    ['To minimize the number of actions taken', 'To maximize the cumulative discounted reward (return) earned over time', 'To predict labels with 100% classification accuracy', 'To memorize all states in RAM'], 1,
    'The agent learns an optimal Policy `π` that maximizes the expected cumulative discounted future reward: `G_t = ∑ (γ^k * R_{t+k+1})`.'),
  q('aiml_rl_3', 'Reinforcement Learning', 'Easy',
    'What does the Discount Factor (γ - gamma, between 0 and 1) represent in RL?',
    ['The discount percentage on cloud computing bills', 'The importance of future rewards relative to immediate rewards (γ=0 considers only immediate rewards; γ near 1 values distant future rewards)', 'The probability of taking a random action', 'The learning rate of the neural network'], 1,
    'The discount factor γ weighs future rewards. If γ=0, the agent is short-sighted (myopic), valuing only instant gratification; as γ approaches 1, it becomes far-sighted, planning long-term strategy.'),
  q('aiml_rl_4', 'Reinforcement Learning', 'Easy',
    'What is a "Policy" (π) in Reinforcement Learning?',
    ['A privacy terms document', 'The mapping or strategy that the agent uses to determine which action to select given a particular state (π(a|s))', 'The rule book written by developers', 'The total score achieved in a game'], 1,
    'A policy defines the agent\'s behavior: deterministic `a = π(s)` or stochastic `π(a|s) = P(A=a | S=s)`, specifying the action to execute in any given state.'),
  q('aiml_rl_5', 'Reinforcement Learning', 'Medium',
    'What is the "Exploration vs Exploitation" dilemma in Reinforcement Learning?',
    ['Choosing between CPU and GPU hardware', 'The fundamental trade-off between trying new, unfamiliar actions to discover potentially higher rewards (Exploration) versus choosing known actions that currently yield the highest known reward (Exploitation)', 'Choosing between supervised and unsupervised learning', 'Deciding whether to save or delete models'], 1,
    'Exploit: use current knowledge to harvest known rewards. Explore: risk sub-optimal actions to discover better global strategies. Balancing both is the central challenge in RL.'),
  q('aiml_rl_6', 'Reinforcement Learning', 'Medium',
    'How does the ε-greedy (epsilon-greedy) strategy balance exploration and exploitation?',
    ['It stops training when errors drop below epsilon', 'With probability (1 - ε), the agent selects the best-known greedy action (exploits); with probability ε, it selects a completely random action (explores)', 'It sets all neural network weights to epsilon', 'It runs epsilon parallel environments'], 1,
    'In ε-greedy: a coin flip with probability ε chooses a random action (exploration), while probability (1 - ε) picks `argmax Q(s, a)` (exploitation), often decaying ε gradually over training.'),
  q('aiml_rl_7', 'Reinforcement Learning', 'Medium',
    'What is a Markov Decision Process (MDP) and what is the "Markov Property"?',
    ['A process for encrypting model weights', 'The Markov Property states that the future state depends strictly on the current state and action, independent of the past history of states ("the future is independent of the past given the present")', 'A model for parallel processing', 'A database query language'], 1,
    'An MDP formalizes RL environments. The Markov Property asserts `P(s_{t+1} | s_t, a_t, s_{t-1}, ... s_0) = P(s_{t+1} | s_t, a_t)`: the current state encapsulates all relevant history.'),
  q('aiml_rl_8', 'Reinforcement Learning', 'Medium',
    'What is the Bellman Equation in Reinforcement Learning?',
    ['An equation calculating gradient descent step size', 'A recursive relationship expressing the value of a state (or state-action pair) as the immediate reward plus the discounted expected value of the successor state', 'An equation calculating neural network training time', 'An algorithm for matrix inversion'], 1,
    'Bellman Equation decomposes the value function into: `V(s) = R(s) + γ * ∑ P(s\'|s,a) * V(s\')`. It is the foundational recursive equation underlying dynamic programming and Q-learning.'),
  q('aiml_rl_9', 'Reinforcement Learning', 'Hard',
    'What is Q-Learning and why is it classified as an "Off-Policy, Model-Free" algorithm?',
    ['It requires a full physics simulation model of the environment', 'Model-Free: it learns optimal action values directly from experience without needing an explicit transition probability model; Off-Policy: it learns the optimal policy Q* while following an exploratory policy (like ε-greedy)', 'It only works with quadratic equations', 'It cannot handle rewards greater than 1'], 1,
    'Model-Free means it doesn\'t model environment transition physics `P(s\'|s,a)`. Off-policy means its update `Q(s,a) += α [r + γ max_a\' Q(s\',a\') - Q(s,a)]` uses the greedy `max` action rather than the action actually taken.'),
  q('aiml_rl_10', 'Reinforcement Learning', 'Hard',
    'What breakthrough did Deep Q-Networks (DQN - DeepMind 2015) introduce to stabilize Q-learning with deep neural networks?',
    ['Replacing Python with assembly language', 'Experience Replay (sampling random past transitions from a buffer to break temporal correlation) and a separate Target Network (updated periodically to stabilize Q-value targets)', 'Eliminating all activation functions', 'Using 1,000 GPUs simultaneously'], 1,
    'Standard Q-learning diverges with neural networks due to correlated samples and moving target values. DQN fixed this with: 1) Replay Buffer (decorrelates training data), and 2) Frozen Target Network (stabilizes Bellman targets).'),

  q('aiml_ev_1', 'Model Evaluation Metrics', 'Easy',
    'What are the four components of a Binary Classification Confusion Matrix?',
    ['Alpha, Beta, Gamma, Delta', 'True Positives (TP), False Positives (FP), True Negatives (TN), and False Negatives (FN)', 'Mean, Median, Mode, Variance', 'Precision, Recall, F1, Loss'], 1,
    'The confusion matrix records: TP (correctly predicted positive), TN (correctly predicted negative), FP (Type I error - false alarm), and FN (Type II error - missed detection).'),
  q('aiml_ev_2', 'Model Evaluation Metrics', 'Easy',
    'What is the formula for Classification Accuracy?',
    ['(TP + FP) / (TN + FN)', '(TP + TN) / (TP + TN + FP + FN)', 'TP / (TP + FP)', 'TP / (TP + FN)'], 1,
    'Accuracy is the ratio of correct predictions to total cases: `(TP + TN) / Total`. It can be misleading in imbalanced datasets.'),
  q('aiml_ev_3', 'Model Evaluation Metrics', 'Easy',
    'What is the definition of "Precision" (Positive Predictive Value)?',
    ['Out of all actual positive cases, how many were detected', 'Out of all instances the model predicted as positive, what fraction was actually positive: TP / (TP + FP)', 'The percentage of true negatives', 'The total number of correct predictions'], 1,
    'Precision answers: "When the model predicts positive, how often is it right?" Formula: `TP / (TP + FP)`. Critical when False Positives are costly (e.g. spam detection).'),
  q('aiml_ev_4', 'Model Evaluation Metrics', 'Easy',
    'What is the definition of "Recall" (Sensitivity / True Positive Rate)?',
    ['Out of all instances predicted positive, how many were right', 'Out of all actual ground-truth positive cases, what fraction was correctly identified: TP / (TP + FN)', 'The fraction of false alarms', 'The ratio of FP to TN'], 1,
    'Recall answers: "Did the model catch all positive cases?" Formula: `TP / (TP + FN)`. Critical when False Negatives are catastrophic (e.g. cancer diagnosis).'),
  q('aiml_ev_5', 'Model Evaluation Metrics', 'Medium',
    'Why is Accuracy a misleading metric on severely imbalanced datasets (e.g. 99% negative, 1% fraudulent transactions)?',
    ['Calculators cannot divide percentages', 'A naive model that predicts "Not Fraud" for every single transaction achieves 99% accuracy while having a disastrous 0% recall on detecting real fraud', 'Accuracy can only evaluate balanced datasets', 'Accuracy cannot be computed on integers'], 1,
    'Accuracy Paradox: in highly skewed datasets, predicting the majority class exclusively produces deceptive near-100% accuracy while failing the core business objective.'),
  q('aiml_ev_6', 'Model Evaluation Metrics', 'Medium',
    'What is the F1-Score and why is it computed as the Harmonic Mean of Precision and Recall instead of Arithmetic Mean?',
    ['It is the average of accuracy and loss', 'F1-Score is `2 * (Precision * Recall) / (Precision + Recall)`; the harmonic mean penalizes extreme disparities heavily, ensuring a high score only if both precision and recall are strong', 'Arithmetic mean cannot handle decimal numbers', 'Harmonic mean runs faster on GPUs'], 1,
    'If a model has Precision=1.0 and Recall=0.0, the arithmetic mean is 0.5 (misleading), but the harmonic mean (F1) is 0.0, punishing models that sacrifice one metric completely.'),
  q('aiml_ev_7', 'Model Evaluation Metrics', 'Medium',
    'What does the ROC (Receiver Operating Characteristic) curve plot, and what does AUC (Area Under Curve) signify?',
    ['Plots Accuracy vs Loss', 'Plots True Positive Rate (Recall) vs False Positive Rate (1 - Specificity) across all classification thresholds; AUC measures discrimination capability (1.0 = perfect, 0.5 = random guess)', 'Plots Training time vs Dataset size', 'Plots Precision vs Learning rate'], 1,
    'The ROC curve illustrates diagnostic ability across all probability cutoffs. AUC-ROC quantifies the probability that the model ranks a random positive example higher than a random negative example.'),
  q('aiml_ev_8', 'Model Evaluation Metrics', 'Medium',
    'What is the difference between Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE) in regression?',
    ['MAE is only for neural networks', 'MAE averages absolute residuals equally; RMSE squares residuals before averaging and square-rooting, penalizing large outlier errors much more severely than MAE', 'RMSE is always smaller than MAE', 'MAE can be negative'], 1,
    'Because RMSE squares differences `(y - y_hat)^2`, large prediction errors disproportionately inflate RMSE, making it sensitive to outliers. MAE treats all linear error magnitudes uniformly.'),
  q('aiml_ev_9', 'Model Evaluation Metrics', 'Hard',
    'What does the Coefficient of Determination (R² Score) measure in regression?',
    ['The correlation coefficient squared without meaning', 'The proportion of variance in the dependent variable that is explained by the independent features in the model (1.0 = perfect prediction, 0.0 = baseline mean model, negative = worse than mean)', 'The percentage of correct predictions', 'The slope of the regression line'], 1,
    '`R² = 1 - (SS_res / SS_tot)`. An R² of 0.85 means 85% of target variability is explained by model inputs. A negative R² indicates the model performs worse than simply predicting the mean target value.'),
  q('aiml_ev_10', 'Model Evaluation Metrics', 'Hard',
    'When should you evaluate models using Precision-Recall (PR) AUC instead of ROC-AUC?',
    ['When features are continuous numbers', 'When dealing with heavily imbalanced datasets where the positive minority class is rare, because ROC-AUC is artificially inflated by high True Negatives, whereas PR-AUC focuses on minority class performance', 'When running on mobile devices', 'When target variable is continuous'], 1,
    'In severe class imbalance (e.g. 1 positive in 10,000), huge TNs keep FPR tiny, producing an artificially optimistic ROC-AUC curve. The PR Curve ignores TNs, directly exposing precision drops on rare positives.')
];

console.log(`Generated ${aimlQuestions.length} initial questions, adding topics 6-15...`);

const aimlTopics6To15 = [

  q('aiml_bv_1', 'Bias-Variance & Overfitting', 'Easy',
    'What is "Overfitting" in machine learning?',
    ['When the training algorithm takes too long to run', 'When a model learns the training data and noise too closely, performing exceptionally well on training data but failing to generalize to unseen test data', 'When a model has too few parameters to capture patterns', 'When data points have missing values'], 1,
    'Overfitting happens when a model memorizes noise and idiosyncrasies in training data (high training accuracy, poor validation/test generalization).'),
  q('aiml_bv_2', 'Bias-Variance & Overfitting', 'Easy',
    'What is "Underfitting"?',
    ['When a model performs poorly on both training data and testing data because it is too simple to capture underlying data relationships', 'When a model achieves 100% test accuracy', 'When a dataset is stored in lowercase', 'When training runs on too few CPU cores'], 0,
    'Underfitting occurs when a model lacks capacity (e.g. fitting a straight line to a complex sine wave), failing to learn underlying structures in both train and test sets.'),
  q('aiml_bv_3', 'Bias-Variance & Overfitting', 'Easy',
    'What is the Bias-Variance Tradeoff?',
    ['Trading accuracy for training speed', 'The tension where simple models have high bias (underfitting) and low variance, while complex models have low bias and high variance (overfitting); total error is minimized at an optimal intermediate complexity', 'Trading cloud costs for RAM', 'Balancing dataset size with image resolution'], 1,
    'Expected prediction error decomposes into: `Bias^2 + Variance + Irreducible Error`. Reducing bias typically increases variance and vice versa; machine learning seeks the sweet spot minimizing combined error.'),
  q('aiml_bv_4', 'Bias-Variance & Overfitting', 'Easy',
    'What is K-Fold Cross-Validation?',
    ['Multiplying dataset size by K', 'Splitting dataset into K equal folds, training on K-1 folds and validating on the remaining fold, repeating K times so every sample is used for validation exactly once', 'Running K neural networks at once', 'Deleting K corrupted rows'], 1,
    'K-Fold cross-validation provides an unbiased estimate of model generalization performance across the entire dataset without wasting data on a single fixed train/test split.'),
  q('aiml_bv_5', 'Bias-Variance & Overfitting', 'Medium',
    'Which of the following techniques helps reduce Overfitting in machine learning models?',
    ['Adding more complex polynomial features', 'Regularization (L1/L2), pruning decision trees, dropout in neural networks, and acquiring more training data', 'Removing validation datasets', 'Increasing training epochs to infinity'], 1,
    'Overfitting remedies: simplify model architecture, apply regularization penalties, apply dropout, prune trees, use early stopping, and augment or collect more training samples.'),
  q('aiml_bv_6', 'Bias-Variance & Overfitting', 'Medium',
    'What is "Data Leakage" and why is it dangerous?',
    ['Hard drives leaking oil', 'When information from outside the training dataset (such as target labels or test-set statistics) inadvertently influences model training, yielding unrealistically optimistic test scores that fail in production', 'Data leaking onto the internet', 'A memory leak in Python'], 1,
    'Data leakage occurs when target-correlated information or test set distributions (e.g. scaling features using the full dataset mean before train/test splitting) bleed into training.'),
  q('aiml_bv_7', 'Bias-Variance & Overfitting', 'Medium',
    'What is "Stratified K-Fold" cross-validation and when is it required?',
    ['Cross-validation on rock layers', 'A variation of K-Fold where each fold preserves the exact percentage/proportion of each target class as present in the complete dataset, essential for imbalanced classification', 'K-Fold with continuous targets only', 'Cross-validation running on multiple servers'], 1,
    'Stratified K-Fold guarantees that rare minority classes (e.g. 2% positive cases) are distributed proportionally across all K folds, preventing folds with zero positive instances.'),
  q('aiml_bv_8', 'Bias-Variance & Overfitting', 'Medium',
    'What does a high training loss and a high validation loss indicate about a model?',
    ['High Variance (Overfitting)', 'High Bias (Underfitting)', 'Optimal generalized model', 'Data Leakage'], 1,
    'When both training and validation losses remain stubbornly high, the model lacks representational capacity to fit the underlying data patterns (High Bias / Underfitting).'),
  q('aiml_bv_9', 'Bias-Variance & Overfitting', 'Hard',
    'What does a low training loss accompanied by a rapidly diverging high validation loss indicate on a learning curve?',
    ['The model is underfitting', 'The model is overfitting: it is continuing to memorize training set noise while losing generalization capability on unseen data', 'The learning rate is too small', 'The model has converged to global optimum'], 1,
    'Divergence between train and validation loss curves is the textbook symptom of overfitting: the network continues to drive training loss toward zero by memorizing training examples, while validation error climbs.'),
  q('aiml_bv_10', 'Bias-Variance & Overfitting', 'Hard',
    'What is the "Double Descent" phenomenon discovered in modern deep neural networks?',
    ['Loss dropping twice in one epoch', 'As model capacity increases beyond the classical interpolation threshold (where training error reaches zero), test error surprisingly decreases again instead of worsening, defying traditional bias-variance intuition', 'A bug in gradient descent', 'When two GPUs train simultaneously'], 1,
    'Modern overparameterized deep networks exhibit Double Descent: test error peaks at the interpolation threshold (classical overfitting) but subsequently descends as capacity expands further, due to implicit regularization of gradient descent.'),

  q('aiml_reg_1', 'Regularization Techniques', 'Easy',
    'What is the primary purpose of Regularization in machine learning?',
    ['To make algorithms run faster', 'To penalize model complexity and prevent overfitting by discouraging excessively large weight values', 'To clean null values in datasets', 'To convert regression to classification'], 1,
    'Regularization adds a penalty term to the loss function based on model parameters, discouraging complex or extreme weights to encourage simpler, generalized models.'),
  q('aiml_reg_2', 'Regularization Techniques', 'Easy',
    'What penalty does L1 Regularization (Lasso) add to the loss function?',
    ['Sum of squared weights (∑ w_i^2)', 'Sum of the absolute values of weights: λ * ∑ |w_i|', 'Product of weights', 'Sum of square roots of weights'], 1,
    'L1 (Lasso) adds the sum of absolute values of weights `λ * ∑|w_i|` to the cost function, driving non-essential feature weights strictly to zero.'),
  q('aiml_reg_3', 'Regularization Techniques', 'Easy',
    'What penalty does L2 Regularization (Ridge / Weight Decay) add to the loss function?',
    ['Sum of absolute values of weights', 'Sum of squared values of weights: (λ/2) * ∑ w_i^2', 'Maximum weight value', 'Inverse of weights'], 1,
    'L2 (Ridge) adds the sum of squared weights `(λ/2) * ∑ w_i^2` to the loss, shrinking weights smoothly toward zero without setting them exactly to zero.'),
  q('aiml_reg_4', 'Regularization Techniques', 'Easy',
    'What unique property makes L1 Regularization (Lasso) useful for Feature Selection?',
    ['It creates new polynomial features', 'It drives less important feature weights exactly to zero, producing sparse models where unneeded features are completely eliminated', 'It doubles the learning rate', 'It groups features into K clusters'], 1,
    'Due to its geometric diamond-shaped constraint boundaries, L1 induces sparsity: coefficients for irrelevant features are driven to absolute zero, acting as automated feature selection.'),
  q('aiml_reg_5', 'Regularization Techniques', 'Medium',
    'What is "Elastic Net" regularization?',
    ['A neural network that stretches with data', 'A linear combination of both L1 (Lasso) and L2 (Ridge) penalties, balancing feature selection with stability for correlated features', 'A regularizer for elastic databases', 'A deep learning activation function'], 1,
    'Elastic Net combines L1 and L2 penalties: `Loss + λ1 * ∑|w| + λ2 * ∑w^2`. It overcomes Lasso\'s limitation of picking only one arbitrary feature among highly correlated variables.'),
  q('aiml_reg_6', 'Regularization Techniques', 'Medium',
    'How does "Dropout" regularize Deep Neural Networks during training?',
    ['By dropping corrupted data rows', 'By randomly setting a fraction `p` of neuron activations to zero during each forward training pass, forcing the network to learn robust redundant representations without co-adapting', 'By dropping slow GPU threads', 'By deleting layers from the network'], 1,
    'Proposed by Hinton, Dropout randomly deactivates neurons during training with probability `p`. This prevents neurons from co-adapting, functioning like an ensemble of thinned sub-networks.'),
  q('aiml_reg_7', 'Regularization Techniques', 'Medium',
    'What must be done to Dropout layers during model Inference / Testing?',
    ['Keep dropout active with 50% probability', 'Deactivate Dropout (all neurons active) and scale weights/outputs by (1 - p) (or use Inverted Dropout during training so no scaling is needed at test time)', 'Delete the dropout layer from memory', 'Set all weights to zero'], 1,
    'At test time, dropout is turned OFF to utilize the full deterministic network. Modern frameworks implement Inverted Dropout during training (scaling by `1/(1-p)`) so test-time inference requires zero adjustments.'),
  q('aiml_reg_8', 'Regularization Techniques', 'Medium',
    'What is "Early Stopping" in neural network training?',
    ['Stopping training when the developer wants lunch', 'Monitoring validation loss after each epoch and halting training when validation loss stops improving for a specified patience window, preventing the model from overfitting', 'Halting training after 1 epoch', 'Terminating when loss reaches exactly 0'], 1,
    'Early stopping acts as a regularizer: it saves the model checkpoint with the lowest validation loss and terminates training when validation loss degrades over `N` consecutive epochs.'),
  q('aiml_reg_9', 'Regularization Techniques', 'Hard',
    'How does "Data Augmentation" (e.g. image flips, crops, color jittering) act as a regularizer?',
    ['By shrinking the neural network layers', 'By artificially expanding the training dataset with label-preserving randomized transformations, exposing the network to diverse variations and reducing its ability to memorize exact training instances', 'By deleting blurry images', 'By converting images to grayscale'], 1,
    'Data augmentation injects realistic domain variations directly into inputs, effectively broadening the training distribution so the network cannot memorize individual pixels, curbing overfitting.'),
  q('aiml_reg_10', 'Regularization Techniques', 'Hard',
    'Why does Batch Normalization exhibit an implicit regularizing effect on deep neural networks?',
    ['It adds L1 penalty to weights', 'Because mini-batch statistics (mean and variance) fluctuate randomly between batches, this stochastic noise added to activations acts similarly to dropout, reducing overfitting', 'It eliminates all learning rates', 'It zeroes out small weights'], 1,
    'Batch Normalization computes mean and variance over stochastic mini-batches rather than the whole dataset. The small random noise introduced into hidden activations prevents extreme reliance on any single neuron.'),

  q('aiml_nn_1', 'Neural Networks Fundamentals', 'Easy',
    'What was the historical "Perceptron" introduced by Frank Rosenblatt?',
    ['A digital camera', 'The simplest artificial neuron model: computes a linear combination of inputs with weights, adds a bias, and passes the sum through a step activation function', 'A multi-layer recurrent network', 'An analog computer monitor'], 1,
    'The Perceptron computes `f(x) = step(w^T * x + b)`. It can separate linearly separable classes (AND, OR) but famously failed on non-linear problems like XOR.'),
  q('aiml_nn_2', 'Neural Networks Fundamentals', 'Easy',
    'Why did the single-layer Perceptron famously fail to solve the XOR (Exclusive OR) problem (Minsky & Papert 1969)?',
    ['Because XOR produces letters instead of numbers', 'Because XOR is not linearly separable (its truth table cannot be separated by a single straight line in 2D space), requiring multi-layer networks with non-linear activations', 'Because computers were too slow', 'Because Perceptrons cannot handle zeros'], 1,
    'XOR outputs 1 for (0,1) and (1,0), and 0 for (0,0) and (1,1). No single linear decision boundary can separate these points, exposing the limitation of single-layer perceptrons.'),
  q('aiml_nn_3', 'Neural Networks Fundamentals', 'Easy',
    'What is the formula for the ReLU (Rectified Linear Unit) activation function?',
    ['f(x) = 1 / (1 + e^-x)', 'f(x) = max(0, x)', 'f(x) = tanh(x)', 'f(x) = x^2'], 1,
    'ReLU is defined as `f(x) = max(0, x)`: it outputs x for positive values and 0 for negative values. It is computationally fast and mitigates vanishing gradients.'),
  q('aiml_nn_4', 'Neural Networks Fundamentals', 'Easy',
    'What is "Forward Propagation" in a neural network?',
    ['Passing gradients backwards from output to input', 'Passing input data forward through successive layers (linear transformations + non-linear activations) to compute final network predictions', 'Moving weights between CPU cores', 'Saving weights to disk'], 1,
    'Forward propagation feeds inputs through successive hidden layers `z = Wx + b; a = σ(z)` until the output layer computes final predictions and the loss function evaluates error against ground truth.'),
  q('aiml_nn_5', 'Neural Networks Fundamentals', 'Medium',
    'What is "Backpropagation" and what mathematical rule is its foundation?',
    ['Multiplying matrices randomly', 'An algorithm that computes the gradient of the loss function with respect to every weight in the network by applying the calculus Chain Rule backwards from the output layer to input layer', 'Solving linear equations with Gaussian elimination', 'Inverting the weight matrix'], 1,
    'Backpropagation applies the calculus Chain Rule repeatedly backwards through layers: `∂L/∂W = (∂L/∂a) * (∂a/∂z) * (∂z/∂W)`, efficiently propagating error gradients to update weights via gradient descent.'),
  q('aiml_nn_6', 'Neural Networks Fundamentals', 'Medium',
    'What is the "Vanishing Gradient Problem" in deep networks using Sigmoid or Tanh activations?',
    ['Gradients becoming larger than infinity', 'The derivatives of Sigmoid/Tanh saturate near 0 for large positive or negative inputs; multiplying these small fractions across deep layers causes gradients to shrink exponentially toward zero, halting learning in early layers', 'Gradients disappearing from RAM', 'Loss function becoming negative'], 1,
    'Sigmoid\'s maximum derivative is 0.25. In deep networks, multiplying numbers <= 0.25 across 10 layers shrinks gradients to virtually zero (`0.25^10 ≈ 10^-6`), preventing early layers from updating weights.'),
  q('aiml_nn_7', 'Neural Networks Fundamentals', 'Medium',
    'What is the "Dying ReLU" problem and how do Leaky ReLU or ELU fix it?',
    ['ReLU neurons overheating the GPU', 'If a large gradient updates weights such that a neuron outputs negative values for all inputs, its gradient becomes permanently 0, rendering the neuron permanently inactive ("dead"); Leaky ReLU provides a small slope (e.g. 0.01x) for negative inputs', 'ReLU deleting training data', 'Neurons losing memory'], 1,
    'When a ReLU neuron gets stuck in the negative regime, its derivative is always 0, so it never updates again. Leaky ReLU `f(x) = max(0.01x, x)` provides a slight gradient for negative values, reviving dead neurons.'),
  q('aiml_nn_8', 'Neural Networks Fundamentals', 'Medium',
    'What does the Softmax activation function do in the final layer of a multi-class neural network?',
    ['Converts numbers to integers', 'Converts an unnormalized vector of real-valued logits into a probability distribution where each value is between 0 and 1 and all values sum up to exactly 1.0', 'Applies L2 regularization', 'Sorts predictions in ascending order'], 1,
    'Softmax computes `e^(z_i) / ∑ e^(z_j)`. It normalizes raw logit outputs into mutually exclusive probabilities across all candidate classes that sum to 1.0.'),
  q('aiml_nn_9', 'Neural Networks Fundamentals', 'Hard',
    'Why must neural network weights be initialized randomly (e.g. Xavier/Glorot or He Initialization) rather than initializing all weights to zero?',
    ['Zero initialization crashes the computer power supply', 'If all weights start at zero, all neurons in a layer compute identical outputs and receive identical gradients during backpropagation (symmetry), failing to learn distinct features', 'Zero weights cause division by zero in loss', 'Weights must always be positive numbers'], 1,
    'Zero initialization causes "Symmetry": every hidden unit computes the exact same activation and receives identical weight updates, functioning as a single neuron regardless of layer width. Random initialization breaks symmetry.'),
  q('aiml_nn_10', 'Neural Networks Fundamentals', 'Hard',
    'What is the difference between Xavier (Glorot) Initialization and He (Kaiming) Initialization?',
    ['Xavier is for GPUs; He is for CPUs', 'Xavier is designed for symmetric activations like Tanh/Sigmoid (variance = 2 / (n_in + n_out)); He initialization is specifically calibrated for non-linear ReLU activations (variance = 2 / n_in) to prevent exploding/vanishing signal variance', 'Xavier initializes weights to zero; He does not', 'They are exact synonyms'], 1,
    'Kaiming He showed that because ReLU zeroes out half of the activations on average, Xavier variance is too small, causing signal decay in deep ReLU networks. He initialization doubles the variance to `2 / n_in`.'),

  q('aiml_opt_1', 'Optimization Algorithms', 'Easy',
    'What is the role of an Optimizer in training machine learning and deep learning models?',
    ['To compile Python code to machine code', 'To iteratively adjust and update model weights and biases in the direction that minimizes the loss function', 'To clean corrupted rows in CSV files', 'To design the user interface'], 1,
    'Optimizers (SGD, Adam) use gradients calculated during backpropagation to update parameters: `W_new = W_old - learning_rate * ∇Loss`.'),
  q('aiml_opt_2', 'Optimization Algorithms', 'Easy',
    'What happens if the Learning Rate (α) is set too high versus too low?',
    ['Too high runs on CPU; too low runs on GPU', 'Too high causes oscillations and can diverge away from the minimum; too low results in agonizingly slow training progress and getting trapped in sub-optimal local minima', 'Too high causes underfitting; too low causes overfitting', 'Learning rate does not affect training'], 1,
    'An excessively large learning rate overshoots the minimum and diverges. An overly small learning rate crawls slowly, risking training stagnation or timeout.'),
  q('aiml_opt_3', 'Optimization Algorithms', 'Easy',
    'What is the difference between Batch Gradient Descent, Stochastic Gradient Descent (SGD), and Mini-Batch Gradient Descent?',
    ['They use different programming languages', 'Batch uses the entire dataset per update (slow, smooth); SGD uses 1 sample per update (fast, noisy); Mini-batch uses small subsets (e.g. 32-256 samples), balancing speed and stable vectorization', 'Mini-batch uses no gradients', 'SGD only works on linear regression'], 1,
    'Batch GD computes gradients across all N samples (memory intensive). Pure SGD updates weights per individual sample (high variance). Mini-Batch GD evaluates batches (32-512) leveraging GPU parallel SIMD matrix acceleration.'),
  q('aiml_opt_4', 'Optimization Algorithms', 'Easy',
    'What does "Momentum" do in Gradient Descent optimization?',
    ['Increases the computer fan speed', 'Accelerates gradient vectors in the relevant direction and dampens oscillations by adding a fraction of the previous step\'s velocity vector to the current update', 'Stops training when loss is 0', 'Multiplies weights by 2'], 1,
    'Momentum mimics a heavy ball rolling down a hill: `v_t = β * v_{t-1} + α * ∇L`. It accumulates speed along consistent downhill gradients while cancelling out lateral oscillations in ravines.'),
  q('aiml_opt_5', 'Optimization Algorithms', 'Medium',
    'What is the Adam (Adaptive Moment Estimation) optimizer and why is it so widely used?',
    ['An AI created by OpenAI', 'An adaptive optimization algorithm that combines the advantages of Momentum (exponential moving average of past gradients) and RMSprop (adaptive learning rates per parameter based on squared gradients)', 'A loss function for images', 'An activation function replacing ReLU'], 1,
    'Adam computes individual adaptive learning rates for each parameter by tracking both first moments (mean / momentum) and second moments (uncentered variance / RMSprop), providing robust convergence across deep learning tasks.'),
  q('aiml_opt_6', 'Optimization Algorithms', 'Medium',
    'What is "Learning Rate Scheduling" (e.g. Cosine Annealing, Step Decay)?',
    ['Setting the alarm clock for training sessions', 'Dynamically decreasing the learning rate over the course of training according to a schedule, allowing fast initial progress followed by fine-grained convergence near the loss minimum', 'Increasing learning rate to infinity', 'Scheduling jobs in Kubernetes'], 1,
    'Starting with a higher learning rate navigates broad loss valleys quickly. Annealing the learning rate down over time enables the optimizer to settle into narrow, sharp minima without overshooting.'),
  q('aiml_opt_7', 'Optimization Algorithms', 'Medium',
    'What is "Weight Decay" in AdamW versus traditional L2 regularization in standard Adam?',
    ['Decomposition of hard drives', 'In AdamW, weight decay is decoupled from the gradient updates and subtracted directly from weights, fixing an issue in standard Adam where L2 regularization was warped by adaptive momentum scalers', 'Weight decay deletes 10% of weights', 'AdamW is an older version of Adam'], 1,
    'Loshchilov & Hutter showed that in standard Adam, L2 penalty interacts incorrectly with adaptive gradient scaling. AdamW decouples weight decay, providing true L2 regularization and superior generalization in Transformers.'),
  q('aiml_opt_8', 'Optimization Algorithms', 'Medium',
    'What is "Gradient Clipping" and what problem does it solve?',
    ['Cropping pictures in computer vision', 'Clamping gradients to a maximum threshold (norm or value) when they exceed a limit, preventing "Exploding Gradients" from destabilizing deep networks (especially RNNs)', 'Deleting small weights', 'Stopping training after 10 epochs'], 1,
    'When backpropagating through deep unrolled networks or RNNs, gradients can multiply exponentially into NaNs (Exploding Gradients). Gradient clipping rescales gradients if `||g|| > threshold`, preserving direction while capping magnitude.'),
  q('aiml_opt_9', 'Optimization Algorithms', 'Hard',
    'Why are "Saddle Points" a bigger challenge than local minima in high-dimensional loss landscapes of deep neural networks?',
    ['Saddle points do not exist in math', 'In thousands of dimensions, true local minima (where all eigenvalues are positive) are exceedingly rare; saddle points (where gradients are zero but some directions slope up and others slope down) are ubiquitous and slow down standard optimizers', 'Saddle points cause GPU memory leaks', 'Saddle points have infinite slope'], 1,
    'In high dimensions, the probability of all orthogonal directions curving upwards simultaneously is vanishingly small. Instead, zero-gradient saddle points dominate, causing standard gradient descent to stall unless momentum/noise escapes them.'),
  q('aiml_opt_10', 'Optimization Algorithms', 'Hard',
    'What is the role of a "Learning Rate Warmup" phase in modern Transformer training?',
    ['Warming up the physical GPU chips with electric current', 'Starting with a very small learning rate and ramping it up linearly over the first few thousand steps before decaying, preventing unstable early gradients from destabilizing uninitialized layer norms and attention weights', 'Running unit tests before training', 'Checking dataset integrity'], 1,
    'In early training, weights are random and gradients are noisy. A large initial step can prematurely push weights into poor landscape regions. Warmup gives the adaptive optimizer time to calibrate statistics before taking large steps.')
];

const finalAiMlList = [...aimlQuestions, ...aimlTopics6To15];

const aimlContent = `// js/data/interviewPrep/aiMl.js
// Complete Question Bank for AI & Machine Learning Fundamentals (15 topics * 10 = 150 MCQs)

window.interviewPrepAiMl = {
  id: 'ai_machine_learning',
  title: 'Artificial Intelligence & Machine Learning',
  icon: 'neurology',
  description: 'Master AI/ML paradigms, supervised & unsupervised learning, reinforcement learning, evaluation metrics, neural networks, optimizers, CNNs, RNNs, and Transformers.',
  totalQuestions: ${finalAiMlList.length},
  topics: [
    'AI vs ML vs Deep Learning',
    'Supervised Learning',
    'Unsupervised Learning',
    'Reinforcement Learning',
    'Model Evaluation Metrics',
    'Bias-Variance & Overfitting',
    'Regularization Techniques',
    'Neural Networks Fundamentals',
    'Optimization Algorithms'
  ],
  questions: ${JSON.stringify(finalAiMlList, null, 2)}
};
`;
fs.writeFileSync(path.join(outDir, 'aiMl.js'), aimlContent);
console.log(`Successfully generated aiMl.js (${finalAiMlList.length} questions across 15 topics)`);
