// scripts/interviewPrep/buildAiMlPart2.js
const fs = require('fs');
const path = require('path');

const targetFile = path.join(__dirname, '../../js/data/interviewPrep/aiMl.js');
let content = fs.readFileSync(targetFile, 'utf8');

function q(id, topic, difficulty, question, options, correctAnswer, explanation) {
  return { id, topic, difficulty, question, options, correctAnswer, explanation };
}

const topics10To15 = [
  // 10. Convolutional Neural Networks & Computer Vision
  q('aiml_cnn_1', 'CNNs & Computer Vision', 'Easy',
    'Why are standard Multi-Layer Perceptrons (MLPs) unsuitable for processing high-resolution images compared to CNNs?',
    ['MLPs cannot multiply numbers', 'MLPs treat every pixel as an independent feature with full connectivity, causing an astronomical explosion of parameters and completely ignoring 2D spatial locality', 'MLPs can only process black and white images', 'MLPs require quantum processors'], 1,
    'A 1000x1000 RGB image has 3 million inputs. Connecting to a hidden layer of 1,000 neurons requires 3 billion weights in an MLP. CNNs solve this via local receptive fields, weight sharing, and spatial translation equivariance.'),
  q('aiml_cnn_2', 'CNNs & Computer Vision', 'Easy',
    'What does a Convolutional Kernel (Filter) do when sliding across an input feature map?',
    ['Deletes every second pixel', 'Computes element-wise dot products between the filter weights and the overlapping local input patch, summing them up with a bias to produce a 2D activation feature map', 'Compresses the image into a JPEG', 'Resizes the image to 32x32'], 1,
    'A convolution slides a small matrix of learnable weights (e.g. 3x3) across the image, computing dot products to detect specific visual features (edges, textures) anywhere in the input.'),
  q('aiml_cnn_3', 'CNNs & Computer Vision', 'Easy',
    'What is the primary function of a "Pooling Layer" (e.g. Max Pooling) in a CNN?',
    ['To normalize RGB values to 1.0', 'To downsample spatial dimensions (height and width), reducing computational parameters and providing slight spatial translation invariance', 'To increase image resolution', 'To connect to the database'], 1,
    'Pooling layers (e.g. 2x2 Max Pooling with stride 2) halve height and width, extracting dominant features while reducing feature map dimensions and preventing overfitting.'),
  q('aiml_cnn_4', 'CNNs & Computer Vision', 'Easy',
    'What is the difference between "Valid Padding" and "Same Padding" in convolutional operations?',
    ['Valid padding is for photos; same padding is for text', 'Valid padding applies zero padding (output shrinks); Same padding pads the input border with zeros so that the output spatial dimensions match the input dimensions', 'Same padding deletes the border pixels', 'They are exact synonyms'], 1,
    'Valid padding adds no padding: `Output = (Input - Filter + 1) / Stride`. Same padding adds enough zero-padding along borders so the spatial output size matches the input size.'),
  q('aiml_cnn_5', 'CNNs & Computer Vision', 'Medium',
    'What architectural innovation did ResNet (Deep Residual Learning - 2015) introduce to train networks over 100 layers deep?',
    ['Using 8K resolution images', 'Skip / Residual Connections (identity shortcuts that add the input `x` directly to the residual mapping `F(x) + x`), allowing gradients to flow unimpeded directly through deep layers during backpropagation', 'Removing all activation functions', 'Replacing GPUs with TPUs'], 1,
    'He et al. introduced Skip Connections: instead of forcing layers to learn `H(x)`, they learn residual `F(x) = H(x) - x`. If layers are redundant, weights easily decay to 0 while identity `x` passes through without vanishing gradients.'),
  q('aiml_cnn_6', 'CNNs & Computer Vision', 'Medium',
    'What is the difference between Object Detection and Semantic Segmentation in computer vision?',
    ['Object detection is for video; segmentation is for audio', 'Object Detection predicts bounding boxes and class labels for individual objects; Semantic Segmentation classifies every individual pixel in the image into a semantic class category', 'Semantic segmentation does not use deep learning', 'Object detection operates in 3D only'], 1,
    'Object detection identifies "where" and "what" via rectangular bounding boxes (e.g. YOLO). Semantic segmentation predicts pixel-level class masks (e.g. U-Net, labeling every road or sky pixel).'),
  q('aiml_cnn_7', 'CNNs & Computer Vision', 'Medium',
    'What does "Translation Invariance" mean in CNN feature extraction?',
    ['The ability to translate text from English to French', 'The property where a feature detector activates identically whether a cat appears in the top-left, center, or bottom-right corner of the image', 'The image does not change file size', 'The camera does not move'], 1,
    'Because convolution weights are shared across all spatial positions, a filter trained to detect an eye or wheel will detect it anywhere it appears in the visual field.'),
  q('aiml_cnn_8', 'CNNs & Computer Vision', 'Medium',
    'What is "Transfer Learning" in Computer Vision (e.g. using ImageNet pre-trained models)?',
    ['Transferring model weights via USB drive', 'Taking a deep network pre-trained on a massive dataset (like ImageNet with 1.4M images) and fine-tuning its learned feature representations on a smaller specialized target dataset', 'Moving code from PyTorch to TensorFlow', 'Transferring images between cloud buckets'], 1,
    'Early layers of deep CNNs learn universal visual primitives (edges, textures, shapes). Reusing these pre-trained weights allows training high-accuracy vision models with only hundreds of domain images.'),
  q('aiml_cnn_9', 'CNNs & Computer Vision', 'Hard',
    'What is a "1x1 Convolution" (Network in Network / Inception) used for?',
    ['It is a pointless operation that does nothing', 'Cross-channel pooling and dimensionality reduction: it reduces or expands the number of feature channels (depth) without altering spatial height and width, drastically cutting compute', 'Detecting 1-pixel errors', 'Replacing all 3x3 filters'], 1,
    'A 1x1 convolution computes linear combinations across all channels at each spatial pixel location, allowing networks to compress 256 channels down to 64 channels before expensive 3x3 or 5x5 spatial convolutions.'),
  q('aiml_cnn_10', 'CNNs & Computer Vision', 'Hard',
    'What is the core breakthrough of the YOLO (You Only Look Once) object detection architecture compared to two-stage detectors (like Faster R-CNN)?',
    ['YOLO uses decision trees instead of neural networks', 'YOLO reframes object detection as a single regression problem from image pixels directly to bounding box coordinates and class probabilities in a single forward pass, achieving real-time 60+ FPS speeds', 'YOLO looks at images twice', 'Faster R-CNN has zero latency'], 1,
    'Two-stage detectors generate region proposals first, then classify each. YOLO divides the image into a grid and predicts all bounding boxes and class probabilities simultaneously in one single forward inference pass.'),

  // 11. Recurrent Neural Networks & Sequence Modeling
  q('aiml_rnn_1', 'RNNs & Sequence Modeling', 'Easy',
    'What is the primary distinguishing characteristic of Recurrent Neural Networks (RNNs)?',
    ['They only process image pixels', 'They maintain an internal hidden state (memory) that loops back into the network, allowing information to persist across sequential input steps over time', 'They have no weights or biases', 'They only run backwards'], 1,
    'RNNs are designed for sequential data (time series, text, audio). The hidden state `h_t = f(W_hh * h_{t-1} + W_xh * x_t)` acts as memory carrying context from previous steps.'),
  q('aiml_rnn_2', 'RNNs & Sequence Modeling', 'Easy',
    'Why do Vanilla RNNs struggle with capturing long-term dependencies in long text sequences?',
    ['Because computers run out of clock cycles', 'Due to vanishing and exploding gradients when backpropagating through time (BPTT) over dozens of sequential steps, causing gradients from early tokens to vanish completely', 'Because RNNs cannot read words', 'Because text has too many letters'], 1,
    'Backpropagation Through Time (BPTT) repeatedly multiplies the recurrent weight matrix `W_hh`. If its eigenvalues are < 1, gradients decay exponentially to 0, leaving the network blind to distant historical context.'),
  q('aiml_rnn_3', 'RNNs & Sequence Modeling', 'Easy',
    'What does LSTM stand for and who designed it to solve vanishing gradients?',
    ['Linear State Transmission Module', 'Long Short-Term Memory, designed by Hochreiter & Schmidhuber (1997)', 'Low Speed Translation Machine', 'Logical Sequence Transformer Model'], 1,
    'LSTM (Long Short-Term Memory) introduced gated memory cells and an additive constant error carousel to overcome the vanishing gradient problem in sequence modeling.'),
  q('aiml_rnn_4', 'RNNs & Sequence Modeling', 'Easy',
    'What are the three core Gates in a standard LSTM cell?',
    ['Start Gate, Pause Gate, End Gate', 'Forget Gate, Input Gate, and Output Gate', 'AND Gate, OR Gate, NOT Gate', 'Alpha Gate, Beta Gate, Delta Gate'], 1,
    'An LSTM cell controls information flow using: 1) Forget Gate (what to discard from cell state), 2) Input Gate (what new info to store in cell state), and 3) Output Gate (what to output to hidden state).'),
  q('aiml_rnn_5', 'RNNs & Sequence Modeling', 'Medium',
    'What is the "Cell State" (C_t) in an LSTM often described as?',
    ['A temporary scratchpad that resets on each token', 'The memory conveyor belt that runs straight down the entire chain with only minor linear interactions, allowing gradients to flow over long sequences without vanishing', 'An external hard drive connection', 'The final output classification probability'], 1,
    'The cell state acts as an internal highway: information flows down the chain with purely additive modifications, enabling error gradients to backpropagate across hundreds of time steps without decaying.'),
  q('aiml_rnn_6', 'RNNs & Sequence Modeling', 'Medium',
    'How does a GRU (Gated Recurrent Unit) simplify the LSTM architecture?',
    ['By removing all gates', 'By merging the Cell State and Hidden State, and replacing the 3 gates with 2 gates: Reset Gate and Update Gate, reducing parameters and computational cost while achieving comparable performance', 'By using only feedforward layers', 'By running without non-linear activations'], 1,
    'Introduced by Cho et al., the GRU eliminates the separate cell state, combining forget and input gates into a single Update Gate, yielding faster training with fewer parameters than LSTM.'),
  q('aiml_rnn_7', 'RNNs & Sequence Modeling', 'Medium',
    'What is a "Bidirectional RNN" (BiRNN)?',
    ['An RNN that trains during both day and night', 'A network combining two independent RNN layers: one processing the sequence forward from start to end, and another processing backward from end to start, capturing both past and future context for each token', 'An RNN running on two GPUs', 'An RNN that predicts two words at once'], 1,
    'In tasks like translation or Named Entity Recognition, context from both preceding and succeeding words matters. A BiRNN concatenates forward hidden state `h_forward` and backward hidden state `h_backward`.'),
  q('aiml_rnn_8', 'RNNs & Sequence Modeling', 'Medium',
    'What is "Teacher Forcing" in training recurrent sequence-to-sequence models?',
    ['Hiring an external human teacher to grade models', 'Feeding the ground-truth target token from the training dataset as the input to the decoder at step `t+1`, rather than feeding the model\'s own generated prediction from step `t`', 'Forcing the learning rate to stay constant', 'Stopping training when the loss reaches 0'], 1,
    'Teacher forcing stabilizes and accelerates decoder training: instead of compounding early prediction mistakes down the chain, the ground-truth sequence is fed directly to guide next-token predictions.'),
  q('aiml_rnn_9', 'RNNs & Sequence Modeling', 'Hard',
    'What was the primary architectural bottleneck of the traditional Seq2Seq Encoder-Decoder model before the Attention mechanism?',
    ['The encoder was too slow to run on GPUs', 'The entire variable-length input sequence was compressed into a single fixed-size context vector, creating an information bottleneck where details of long sentences were lost', 'The decoder could only output numbers', 'The model could not handle nouns'], 1,
    'In classic Seq2Seq (Sutskever et al.), the final encoder hidden state was a fixed-length bottleneck vector. As sentences exceeded 20 words, representation quality deteriorated catastrophically.'),
  q('aiml_rnn_10', 'RNNs & Sequence Modeling', 'Hard',
    'Why can RNNs and LSTMs NOT be parallelized across sequence steps during training, unlike Transformers?',
    ['Because RNN code is written in Python', 'Because the computation of step `t` strictly requires the output hidden state `h_{t-1}` from the previous step, enforcing sequential execution that cannot exploit GPU parallelization across time', 'Because GPUs only support 2D arrays', 'Because sequence lengths are unpredictable'], 1,
    'RNNs have inherently sequential temporal dependencies: you cannot compute token 50 before token 49 finishes. Transformers eliminate recurrent recurrence entirely, enabling massive simultaneous GPU parallelization over all tokens.'),

  // 12. Transformer Architecture & Self-Attention
  q('aiml_tf_1', 'Transformer & Self-Attention', 'Easy',
    'What is the seminal 2017 research paper by Vaswani et al. that introduced the Transformer architecture?',
    ['"Deep Residual Learning for Image Recognition"', '"Attention Is All You Need"', '"Language Models are Few-Shot Learners"', '"Mastering the Game of Go"'], 1,
    'Google researchers published "Attention Is All You Need" at NeurIPS 2017, introducing the Transformer and replacing recurrence with self-attention.'),
  q('aiml_tf_2', 'Transformer & Self-Attention', 'Easy',
    'What are the three vectors created by linear projections for each input token in Scaled Dot-Product Attention?',
    ['Alpha, Beta, Gamma', 'Query (Q), Key (K), and Value (V)', 'Weights, Biases, Gradients', 'Input, Hidden, Output'], 1,
    'In self-attention, each token representation is projected into three distinct spaces: Query (what the token is searching for), Key (what the token contains), and Value (the actual content representation).'),
  q('aiml_tf_3', 'Transformer & Self-Attention', 'Easy',
    'What is the exact mathematical formula for Scaled Dot-Product Attention?',
    ['Attention(Q, K, V) = Q * K * V', 'Attention(Q, K, V) = softmax( (Q * K^T) / sqrt(d_k) ) * V', 'Attention(Q, K, V) = sigmoid(Q + K + V)', 'Attention(Q, K, V) = ReLU(Q * K) / V'], 1,
    'Scaled dot-product attention computes compatibility between queries and keys, scales by `1/sqrt(d_k)` to prevent softmax saturation, applies softmax, and computes a weighted sum of values `V`.'),
  q('aiml_tf_4', 'Transformer & Self-Attention', 'Easy',
    'Why does the attention formula divide by `sqrt(d_k)` (square root of the key dimension)?',
    ['To convert numbers to integers', 'For large dimensions `d_k`, dot products grow large in magnitude, pushing softmax into regions with extremely small gradients; scaling by `sqrt(d_k)` keeps gradients stable', 'To reduce training time by half', 'To normalize token lengths'], 1,
    'When `d_k` is large, the variance of the dot product is `d_k`. Dividing by `sqrt(d_k)` restores unit variance, preventing the softmax function from saturating into regions with vanishing gradients.'),
  q('aiml_tf_5', 'Transformer & Self-Attention', 'Medium',
    'Why do Transformers require "Positional Encodings" added to token embeddings?',
    ['To encrypt token identities', 'Because self-attention operations are permutation-equivariant (they process all tokens simultaneously with zero inherent awareness of word order or sequence position)', 'To increase vocabulary size', 'To distinguish nouns from verbs'], 1,
    'Unlike RNNs which process words step-by-step, self-attention treats inputs as an unordered set of tokens. Positional encodings (sinusoidal or learned) inject word order information into embeddings.'),
  q('aiml_tf_6', 'Transformer & Self-Attention', 'Medium',
    'What is "Multi-Head Attention" and what is its advantage over single-head attention?',
    ['Running attention on multiple computers', 'Projecting Q, K, V into multiple representation subspaces in parallel, allowing the model to jointly attend to information from different representation aspects (e.g. grammar, semantics, reference) simultaneously', 'Running 8 different language models at once', 'Using 8 separate GPUs'], 1,
    'Multi-head attention splits the embedding dimension into `h` parallel heads. Each head specializes in capturing different linguistic relationships (e.g. subject-verb agreement vs coreference resolution).'),
  q('aiml_tf_7', 'Transformer & Self-Attention', 'Medium',
    'What does "Causal Masking" (Masked Self-Attention) do in autoregressive Transformer Decoders (like GPT)?',
    ['Hides user passwords in the prompt', 'Sets attention scores to -infinity for future tokens (`j > i`), preventing current tokens from attending to upcoming future words during autoregressive text generation', 'Masks 15% of words randomly', 'Deletes empty spaces in text'], 1,
    'In generative decoders (GPT), causal masking ensures the prediction for token `i` depends strictly on known preceding tokens `0 ... i`, preventing the model from "cheating" by peeking at future tokens.'),
  q('aiml_tf_8', 'Transformer & Self-Attention', 'Medium',
    'What is the computational complexity of standard Full Self-Attention with respect to sequence length N?',
    ['O(N)', 'O(N^2) (Quadratic in sequence length)', 'O(log N)', 'O(N^3)'], 1,
    'Computing the NxN attention matrix requires evaluating dot products between every pair of tokens, scaling quadratically in compute and memory `O(N^2)`, which creates a bottleneck for very long contexts.'),
  q('aiml_tf_9', 'Transformer & Self-Attention', 'Hard',
    'What is the difference between "Pre-LayerNorm" and "Post-LayerNorm" in Transformer blocks and why do modern LLMs prefer Pre-LayerNorm?',
    ['Pre-LayerNorm is only for vision', 'Post-LN normalizes after the residual addition (unstable, requires warmup); Pre-LN applies LayerNorm before self-attention and MLP blocks inside the residual branch, allowing smooth gradient flow and stable training without warmup', 'Pre-LN removes all layer norms', 'Post-LN is faster on CPUs'], 1,
    'In original Transformers (Post-LN), gradients pass through LayerNorm, making deep training unstable. Modern architectures (Llama, GPT-3) use Pre-LN, creating an unimpeded identity residual pathway for gradients.'),
  q('aiml_tf_10', 'Transformer & Self-Attention', 'Hard',
    'What is FlashAttention (Dao et al.) and how does it accelerate Transformer training without changing attention mathematically?',
    ['It quantizes weights to 4 bits', 'An IO-aware exact attention algorithm that tiles the computation into GPU High-Bandwidth Memory (HBM) and fast SRAM blocks using online softmax, eliminating slow intermediate reading/writing of the NxN attention matrix', 'An approximation of attention using FFT', 'A tool for compressing prompts'], 1,
    'FlashAttention recognizes that GPU memory bandwidth is the real bottleneck. By tiling Q, K, V blocks in fast on-chip SRAM and computing softmax incrementally, it avoids materializing the giant NxN matrix in HBM, speeding up training 2-4x.')
];

const topics13To15 = [
  // 13. NLP Fundamentals
  q('aiml_nlp_1', 'NLP Fundamentals', 'Easy',
    'What is "Tokenization" in Natural Language Processing?',
    ['Converting words into audio sounds', 'The process of splitting raw text strings into discrete units (tokens) such as words, subwords, or characters to be converted into numerical IDs', 'Translating text to another language', 'Encrypting text with AES'], 1,
    'Tokenization breaks continuous strings into discrete token chunks (e.g. using Byte-Pair Encoding or WordPiece) that map to integer IDs in a vocabulary dictionary.'),
  q('aiml_nlp_2', 'NLP Fundamentals', 'Easy',
    'What is Byte-Pair Encoding (BPE) tokenization?',
    ['Compressing text into zip files', 'A subword tokenization algorithm that iteratively merges the most frequently occurring adjacent pairs of bytes/characters, balancing vocabulary size and out-of-vocabulary (OOV) words', 'A binary encryption protocol', 'A spelling correction tool'], 1,
    'BPE starts with individual characters and merges common pairs (e.g. "l" + "o" -> "lo" -> "low"). Common words stay whole, while rare words break into meaningful subwords, eliminating OOV issues.'),
  q('aiml_nlp_3', 'NLP Fundamentals', 'Easy',
    'What is a "Word Embedding" (e.g. Word2Vec, GloVe)?',
    ['A dictionary definition of a word', 'A dense, continuous low-dimensional vector representation of words where semantically similar words map to nearby geometric points in vector space', 'An HTML tag for embedding text', 'A list of synonyms'], 1,
    'Word embeddings map words to dense vectors (e.g. 300 dimensions). Semantic relationships are preserved geometrically (e.g. `vector("King") - vector("Man") + vector("Woman") ≈ vector("Queen")`).'),
  q('aiml_nlp_4', 'NLP Fundamentals', 'Easy',
    'What are the two training architectures introduced in Word2Vec (Mikolov et al. 2013)?',
    ['Alpha and Beta', 'Continuous Bag of Words (CBOW - predicts target word from context) and Skip-gram (predicts context words from target word)', 'Supervised and Unsupervised', 'Encoder and Decoder'], 1,
    'Word2Vec has two models: CBOW predicts the center word given surrounding context words. Skip-Gram uses the center word to predict its neighboring context words.'),
  q('aiml_nlp_5', 'NLP Fundamentals', 'Medium',
    'What is the fundamental architectural difference between BERT and GPT?',
    ['BERT is written in C; GPT in Python', 'BERT is an Encoder-only bidirectional model trained with Masked Language Modeling (ideal for classification and understanding); GPT is a Decoder-only autoregressive causal model trained to predict next tokens (ideal for generation)', 'BERT cannot process English', 'GPT does not use Transformers'], 1,
    'BERT reads bidirectional context simultaneously (left and right) to understand text. GPT uses unidirectional causal masking to generate coherent text sequentially from left to right.'),
  q('aiml_nlp_6', 'NLP Fundamentals', 'Medium',
    'What is "Cosine Similarity" and why is it preferred over Euclidean distance for comparing text embeddings?',
    ['Cosine similarity is faster on Intel CPUs', 'Cosine similarity measures the cosine of the angle between two vectors, capturing orientation/semantic alignment independent of vector magnitude (document length)', 'Euclidean distance cannot handle negative numbers', 'Cosine similarity only works on 2D vectors'], 1,
    '`Cosine_Sim = (A · B) / (||A|| * ||B||)`. It evaluates semantic direction: long and short documents covering the identical topic point in the same direction, which Euclidean distance would misjudge based on word count.'),
  q('aiml_nlp_7', 'NLP Fundamentals', 'Medium',
    'What was the training objective of BERT\'s Masked Language Model (MLM)?',
    ['Translating English to Spanish', 'Randomly masking 15% of input tokens with a `[MASK]` token and training the deep bidirectional encoder to predict the original identity of the masked words based on left and right context', 'Predicting the sentiment of sentences', 'Sorting sentences in chronological order'], 1,
    'MLM randomly replaces words with `[MASK]`. Because the model can look at all other tokens in the sentence simultaneously, it learns deep contextual bidirectional representations.'),
  q('aiml_nlp_8', 'NLP Fundamentals', 'Medium',
    'What is TF-IDF (Term Frequency - Inverse Document Frequency)?',
    ['A deep learning library', 'A statistical numerical statistic intended to reflect how important a word is to a document in a collection: high for words frequent in one document but rare across the entire corpus', 'A tokenization algorithm for LLMs', 'A GPU driver for NLP'], 1,
    'TF measures how often a word appears in a text. IDF penalizes universally common words ("the", "is"). The product highlights words that characterize specific documents.'),
  q('aiml_nlp_9', 'NLP Fundamentals', 'Hard',
    'What is "Cross-Attention" in sequence-to-sequence Transformers (e.g. translation)?',
    ['Attention between two different GPUs', 'An attention layer where Queries come from the previous decoder layer, while Keys and Values come from the final output representations of the Encoder', 'Attention that crosses between languages without words', 'A masked self-attention layer'], 1,
    'In encoder-decoder Transformers, Cross-Attention allows the decoder generating translated words to query the source sentence representations produced by the encoder.'),
  q('aiml_nlp_10', 'NLP Fundamentals', 'Hard',
    'What are Contextual Word Embeddings (ELMo, BERT) compared to Static Word Embeddings (Word2Vec, GloVe)?',
    ['Contextual embeddings are stored in cloud databases', 'Static embeddings assign a single fixed vector per word regardless of context (the word "apple" has the same vector in "eating an apple" and "Apple stock"); Contextual embeddings generate dynamic representations based on surrounding context', 'Static embeddings require Transformers', 'Contextual embeddings cannot handle numbers'], 1,
    'Word2Vec gives polysemous words ("bank" of a river vs "bank" for money) the exact same vector. Contextual models dynamically compute representations based on sentence context.'),

  // 14. LLMs & Generative AI
  q('aiml_llm_1', 'LLMs & Generative AI', 'Easy',
    'What does LLM stand for in modern AI?',
    ['Low-Latency Machine', 'Large Language Model', 'Linear Logic Matrix', 'Logical Learning Mechanism'], 1,
    'LLM stands for Large Language Model: deep learning models with billions of parameters trained on vast corpora of text (e.g. GPT-4, Llama 3, Gemini).'),
  q('aiml_llm_2', 'LLMs & Generative AI', 'Easy',
    'What is "Prompt Engineering"?',
    ['Designing computer hardware for AI', 'The craft of formulating, structuring, and optimizing natural language inputs and instructions to guide generative AI models to produce desired, accurate outputs', 'Writing Python code to train models', 'Debugging neural network gradients'], 1,
    'Prompt engineering designs effective prompts (system prompts, role assignment, few-shot examples, chain-of-thought) to steer LLM responses accurately without changing weights.'),
  q('aiml_llm_3', 'LLMs & Generative AI', 'Easy',
    'What is RAG (Retrieval-Augmented Generation)?',
    ['An image generation algorithm', 'An architecture that retrieves relevant authoritative documents from an external knowledge base/vector database and feeds them into the LLM context prompt to generate grounded, accurate responses', 'A technique for training models without data', 'A method to compress LLMs into small files'], 1,
    'RAG grounds LLMs on external private or up-to-date data: 1) Query retrieves top-K chunks from vector DB; 2) Chunks are injected into prompt; 3) LLM generates hallucination-free answers citing sources.'),
  q('aiml_llm_4', 'LLMs & Generative AI', 'Easy',
    'What does the "Temperature" parameter control during LLM text generation?',
    ['The physical temperature of the server rack', 'The randomness and creativity of next-token sampling (temperature near 0 produces deterministic, focused outputs; higher temperature produces diverse, creative outputs)', 'The speed of text generation', 'The maximum context window length'], 1,
    'Temperature scales logits before softmax: `P(x) = softmax(logits / T)`. Low T sharpens probability peaks (deterministic). High T flattens the distribution, encouraging creative word choices.'),
  q('aiml_llm_5', 'LLMs & Generative AI', 'Medium',
    'What is "Hallucination" in Large Language Models?',
    ['A user experiencing visual glitches', 'When an LLM confidently generates information that is factually incorrect, nonsensical, or ungrounded in real-world facts or provided source material', 'When an LLM runs out of GPU memory', 'When training loss reaches negative values'], 1,
    'Hallucinations occur because LLMs are statistical next-token predictors optimizing plausibility rather than ground truth, producing plausible-sounding factual errors.'),
  q('aiml_llm_6', 'LLMs & Generative AI', 'Medium',
    'What is "Few-Shot Prompting" compared to "Zero-Shot Prompting"?',
    ['Shooting pictures with cameras', 'Zero-shot asks the model to perform a task with instructions only; Few-shot provides a few demonstration input-output example pairs in the prompt before the final question to guide formatting and logic', 'Few-shot trains the model weights', 'Zero-shot uses zero parameters'], 1,
    'In-context learning: Few-shot prompting provides 2-5 explicit demonstration examples directly in the prompt text, conditioning the LLM to mirror the desired style and logic without fine-tuning.'),
  q('aiml_llm_7', 'LLMs & Generative AI', 'Medium',
    'What is LoRA (Low-Rank Adaptation) in parameter-efficient fine-tuning (PEFT)?',
    ['A low-cost cloud provider', 'A technique that freezes pre-trained model weights and injects trainable rank-decomposition matrices (A and B) into attention layers, reducing trainable parameters by 99% while matching full fine-tuning performance', 'A tool for quantizing models to 8 bits', 'A prompt engineering template'], 1,
    'LoRA decomposes weight updates `ΔW = B * A` (where rank `r << d`). Training a 70B parameter model with LoRA requires tuning only a few megabytes of adapter weights instead of hundreds of gigabytes.'),
  q('aiml_llm_8', 'LLMs & Generative AI', 'Medium',
    'What is RLHF (Reinforcement Learning from Human Feedback) in LLM alignment (e.g. InstructGPT / ChatGPT)?',
    ['Paying humans to write code', 'A 3-step alignment process: 1) Supervised fine-tuning, 2) Training a Reward Model on human preference comparisons, 3) Optimizing the policy LLM against the reward model using PPO (Proximal Policy Optimization)', 'Testing models with automated unit tests', 'A tool that deletes toxic words'], 1,
    'RLHF aligns raw base models with human intent (Helpful, Honest, Harmless) by training a Reward Model on human pair-wise rankings, then using RL (PPO) to maximize the reward score.'),
  q('aiml_llm_9', 'LLMs & Generative AI', 'Hard',
    'What is "Chain-of-Thought" (CoT) prompting (Wei et al. 2022) and why does it improve multi-step reasoning?',
    ['Prompting models with chains of text files', 'Encouraging the LLM to output explicit intermediate reasoning steps before arriving at the final answer ("Let\'s think step by step"), allocating more computation tokens to complex logical reasoning', 'Connecting multiple LLMs in a loop', 'Using recursive prompt templates'], 1,
    'Because Transformers generate one token at a time, forcing the model to verbalize intermediate reasoning steps ("Chain of Thought") effectively allows it to spend more forward-pass compute exploring logical inferences before answering.'),
  q('aiml_llm_10', 'LLMs & Generative AI', 'Hard',
    'What is Model Quantization (e.g. 4-bit / 8-bit quantization like AWQ, GPTQ, GGUF)?',
    ['Rounding numbers to the nearest integer', 'Converting model weights and activations from high-precision floating point (FP32/FP16) into lower-precision integers (INT8/INT4), slashing GPU memory requirements by 50-75% with minimal accuracy loss', 'Deleting 4 out of every 8 layers', 'Splitting models across 4 GPUs'], 1,
    'Quantization maps continuous 16-bit floats to compact 4-bit/8-bit integers. This allows a 70B parameter model (needing ~140 GB VRAM in FP16) to fit comfortably onto consumer GPUs (~35-40 GB in 4-bit) with near-lossless accuracy.'),

  // 15. Ethical AI, Bias & Model Deployment (MLOps)
  q('aiml_mlops_1', 'Ethical AI & MLOps', 'Easy',
    'What does MLOps stand for and what is its goal?',
    ['Machine Learning Operations: applying DevOps principles (CI/CD, versioning, monitoring) to automate the deployment, monitoring, and lifecycle management of machine learning models in production', 'Machine Language Optimizers', 'Microservice Load Operations', 'Model Loss Optimizers'], 0,
    'MLOps unifies machine learning system development (ML) and system operations (Ops) to standardize continuous integration, deployment, versioning, and monitoring of ML models reliably.'),
  q('aiml_mlops_2', 'Ethical AI & MLOps', 'Easy',
    'What is "Algorithmic Bias" in artificial intelligence systems?',
    ['A compiler error in Python', 'Systematic and repeatable errors in computer systems that create unfair outcomes, such as privileging one arbitrary group of users over others (often reflecting historical prejudices present in training data)', 'A model with high bias and low variance', 'A preference for GPU hardware'], 1,
    'AI models mirror the data they are fed: if training data contains historical societal biases or underrepresents specific demographics, the model amplifies those disparities in loan approvals, hiring, or facial recognition.'),
  q('aiml_mlops_3', 'Ethical AI & MLOps', 'Easy',
    'What is "Concept Drift" in production machine learning systems?',
    ['A drift car simulation game', 'When the statistical properties of the target variable change over time in unforeseen ways, degrading model prediction accuracy in production (e.g. consumer buying habits changing after an economic crisis)', 'A memory leak in production servers', 'When developers change the model architecture'], 1,
    'Concept drift occurs when the underlying relationship between inputs X and target Y evolves over time (`P(Y|X)` changes), requiring automated monitoring and model retraining.'),
  q('aiml_mlops_4', 'Ethical AI & MLOps', 'Easy',
    'What is a "Vector Database" (e.g. Pinecone, Weaviate, Milvus, Chroma)?',
    ['A database that stores 2D vector graphics', 'A specialized database engineered to index, store, and query high-dimensional vector embeddings using Approximate Nearest Neighbor (ANN) search algorithms (like HNSW)', 'A database for math teachers', 'A database running on vector GPUs'], 1,
    'Vector databases store embedding representations of text/images, supporting ultra-fast sub-millisecond similarity queries across millions of vectors using algorithms like Hierarchical Navigable Small World (HNSW).'),
  q('aiml_mlops_5', 'Ethical AI & MLOps', 'Medium',
    'What is ONNX (Open Neural Network Exchange)?',
    ['A cryptocurrency for AI', 'An open, vendor-neutral ecosystem format that allows AI models to be exported from one framework (PyTorch, TensorFlow) and deployed seamlessly across heterogeneous runtimes and hardware (ONNX Runtime)', 'A programming language replacing C++', 'A cloud hosting service for models'], 1,
    'ONNX provides a universal intermediate representation for neural network graphs, enabling seamless cross-platform deployment (e.g. train in PyTorch, deploy optimized C++ inference on edge hardware).'),
  q('aiml_mlops_6', 'Ethical AI & MLOps', 'Medium',
    'What is "Data Drift" (Covariate Shift) compared to Concept Drift?',
    ['Data drift changes target definitions', 'Data Drift occurs when the statistical distribution of input features `P(X)` changes over time while the conditional probability `P(Y|X)` remains the same (e.g. new user demographics entering the app)', 'Data drift means data was deleted', 'They are exact synonyms'], 1,
    'In Covariate Shift / Data Drift, input feature distributions shift (`P(X)` changes), but the underlying relationship to the target stays constant. Monitoring distributions via Kolmogorov-Smirnov tests detects data drift.'),
  q('aiml_mlops_7', 'Ethical AI & MLOps', 'Medium',
    'What is a "Model Registry" (e.g. MLflow Model Registry)?',
    ['A list of developer names', 'A centralized repository providing collaborative model lifecycle management, versioning, stage transitions (Staging -> Production -> Archived), and lineage tracking for production models', 'A government database of AI patents', 'A tool that compiles Python to C'], 1,
    'A Model Registry tracks trained model artifacts, hyperparameters, metrics, and versions, providing formal promotion workflows and auditing before deploying models to live endpoints.'),
  q('aiml_mlops_8', 'Ethical AI & MLOps', 'Medium',
    'What is "Shadow Deployment" (Dark Launch) for ML models in production?',
    ['Deploying models at night', 'Deploying a new model candidate alongside the existing production model; incoming live traffic is duplicated and sent to both, but only the active model\'s predictions are returned to users while the shadow model is monitored for accuracy/latency', 'Deploying an encrypted model', 'Deploying models without internet access'], 1,
    'Shadow deployments test new models on real production traffic with zero user risk: predictions are logged and benchmarked against ground truth without impacting the customer experience.'),
  q('aiml_mlops_9', 'Ethical AI & MLOps', 'Hard',
    'What are SHAP (SHapley Additive exPlanations) and LIME used for in Explainable AI (XAI)?',
    ['To accelerate GPU matrix multiplication', 'Model-agnostic interpretability tools that explain the output of complex black-box machine learning models by quantifying the positive or negative contribution of each feature to a specific prediction', 'To compress deep neural networks', 'To generate synthetic training data'], 1,
    'SHAP (rooted in cooperative game theory) and LIME approximate local decision boundaries, calculating exactly how much each feature (e.g. income +$500, credit score -20) shifted the model\'s prediction away from base value.'),
  q('aiml_mlops_10', 'Ethical AI & MLOps', 'Hard',
    'What is a "Prompt Injection" security attack against LLM applications and how is it mitigated?',
    ['Injecting physical cables into the server', 'An attack where an adversary crafts malicious inputs that override or manipulate the system prompt and security guardrails of the LLM (e.g. "Ignore previous instructions and do X"); mitigated using input sanitization, dual LLM verifiers, and structured function calling', 'Injecting SQL statements into databases', 'Cracking LLM encryption keys'], 1,
    'Prompt injection exploits the lack of separation between code (instructions) and data (user input) in LLMs. Attackers trick the model into breaking guardrails, exfiltrating system prompts or taking unauthorized actions.')
];

// Combine all 150 questions
const complete150 = [...JSON.parse(content.substring(content.indexOf('questions: [') + 11, content.lastIndexOf(']') + 1)), ...topics10To15, ...topics13To15];

console.log(`Total questions compiled: ${complete150.length}`);

const finalAiMlContent = `// js/data/interviewPrep/aiMl.js
// Complete Question Bank for AI & Machine Learning Fundamentals (15 topics * 10 = 150 MCQs)

window.interviewPrepAiMl = {
  id: 'ai_machine_learning',
  title: 'Artificial Intelligence & Machine Learning',
  icon: 'neurology',
  description: 'Master AI/ML paradigms, supervised & unsupervised learning, reinforcement learning, evaluation metrics, neural networks, optimizers, CNNs, RNNs, Transformers, NLP, LLMs, and MLOps.',
  totalQuestions: ${complete150.length},
  topics: [
    'AI vs ML vs Deep Learning',
    'Supervised Learning',
    'Unsupervised Learning',
    'Reinforcement Learning',
    'Model Evaluation Metrics',
    'Bias-Variance & Overfitting',
    'Regularization Techniques',
    'Neural Networks Fundamentals',
    'Optimization Algorithms',
    'CNNs & Computer Vision',
    'RNNs & Sequence Modeling',
    'Transformer & Self-Attention',
    'NLP Fundamentals',
    'LLMs & Generative AI',
    'Ethical AI & MLOps'
  ],
  questions: ${JSON.stringify(complete150, null, 2)}
};
`;

fs.writeFileSync(targetFile, finalAiMlContent);
console.log(`Successfully updated aiMl.js with ${complete150.length} questions across 15 topics.`);
